# Generated by Django 3.2.16 on 2023-05-28 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.TextField()),
                ('modelo', models.TextField()),
                ('rom', models.JSONField()),
                ('ram', models.JSONField()),
                ('bateria', models.IntegerField()),
                ('puntuacion', models.FloatField()),
                ('precio', models.FloatField()),
                ('imagen', models.TextField()),
                ('es_favorito', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'movil')},
            },
        ),
    ]
